server:
  port: 8082
spring:
  application:
    name: estoque-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/estoque}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:89327934}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: estoque-service-v1
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "br.com.logiflow.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: br.com.logiflow.estoque.event.PedidoCriadoEvent
    listener:
      ack-mode: record
management:
  endpoints.web.exposure.include: health,info,metrics
logiflow:
  topics:
    pedido-criado: logiflow.pedidos.criados.v1
    reserva-confirmada: logiflow.reservas.confirmadas.v1
  outbox:
    fixed-delay: 2000
